version: "3.3"

services:

   jenkins:
      image: jenkinsci/blueocean
      privileged: true
      user: root
      ports:
         - 8080:8080
         - 50000:50000
      container_name: jenkins
      volumes:
         - /home/jenkins/data:/var/jenkins_home
         - /var/run/docker.sock:/var/run/docker.sock

   sonar:
      image: sonarqube:latest
      container_name: sonar
      ports:
         - 9000:9000
      volumes:
         -/home/sonarqube/data:/opt/sonarqube/data
      restart: on-failure 

   nexus:
      image: sonatype/nexus3:latest
      container_name: nexus
      ports:
         -8081:8081
         -8088:8088
      volumes:
         - /home/nexus/nexus-data:/nexus-data
